### ISSUE TITLE
Is it possible to launch the Wii system menu?

### ISSUE THREAD

**Issue by mariomadproductions** [timefox/TeconMoon-s-WiiVC-Injector-Mod#10]
Is it possible to launch the Wii system menu, rather than loading specific titles?

**Comment by timefox** [comment]
Yes, of course. I think that Nintendo has already provided this feature officially. You can click the icon of "wii" in wiiu menu, it will bring you to vWII mode straightly.

**Comment by mariomadproductions** [comment]
I meant while also making use of the features provided by this tool.

**Comment by timefox** [comment]
This tool is used to inject Wii titles. So all features it provided are related to titles injection. Did you mean to make a injcetor which can run in Wii U or need the features like 'switch gamepad emulation mode at runtime of the titles'? I'm not quite sure what you mean. If you mean the same thing as I mentioned above, I wouldn't say it's totally impossible but it's beyond the scope of this tool.

**Comment by mariomadproductions** [comment]
Basically, I'd like to try launching the system menu title. So could you make it so you can input the full 16-digit hexedecimal title id instead of just the 4-character ASCII title ID low?

**Comment by mariomadproductions** [comment]
I'll open a new issue for this.
