### ISSUE TITLE
Title ID is restricted for vWii titles

### ISSUE THREAD

**Issue by mariomadproductions** [timefox/TeconMoon-s-WiiVC-Injector-Mod#12]
The app doesn't let me input any title ID. Its limited to title highs of of "00010001" and title ids lows that can be represented by ASCII letters/numbers.

**Comment by timefox** [comment]
Indeed, if this is the problem you mentioned in issue#10, you can modify the full 16-digit hexedecimal title id at 'GamePad/Meta Options' - 'Pre-generated Title ID' for any injection type.

**Comment by mariomadproductions** [comment]
Sorry, I meant the vWii title id to be launched.

**Comment by timefox** [comment]
vWii title id you input is just translated to the last 8 hex chars in 'Pre-generated Title ID'. And '00050002' is given as the first 8 chars by default. Other than that, there's nowhere else this ID is used. You can change ‘Pre-generated Title ID’ to any vWii title id you want to lanuch freely. The limitation on this id input is a part of 'Noob Portection'.

**Comment by mariomadproductions** [comment]
Ah I see, the launched vWii title is based on the Wii U title's title ID.

**Comment by timefox** [comment]
Yes, it is. So I think that we can close this issue now.
