### ISSUE TITLE
Problem with JNUSTool

### ISSUE THREAD

**Issue by BerserkSoul1989** [timefox/TeconMoon-s-WiiVC-Injector-Mod#14]
Hi there :D

Have some issues with this mod and the original. It always stuck on this screen
https://imgur.com/gallery/sDjaWUk

**Comment by timefox** [comment]
The injector will try to download some required base files from nintendo shop's official site by JNUSTool, and save them to '%ALLUSERSPROFILE%\JNUSToolDownloads'.
Here is the file list:
                "0005001010004000\\code\\deint.txt",
                "0005001010004000\\code\\font.bin",
                "0005001010004001\\code\\c2w.img",
                "0005001010004001\\code\\boot.bin",
                "0005001010004001\\code\\dmcu.d.hex",
                "Rhythm Heaven Fever [VAKE01]\\code\\cos.xml",
                "Rhythm Heaven Fever [VAKE01]\\code\\frisbiiU.rpx",
                "Rhythm Heaven Fever [VAKE01]\\code\\fw.img",
                "Rhythm Heaven Fever [VAKE01]\\code\\fw.tmd",
                "Rhythm Heaven Fever [VAKE01]\\code\\htk.bin",
                "Rhythm Heaven Fever [VAKE01]\\code\\nn_hai_user.rpl",
                "Rhythm Heaven Fever [VAKE01]\\content\\assets\\shaders\\cafe\\banner.gsh",
                "Rhythm Heaven Fever [VAKE01]\\content\\assets\\shaders\\cafe\\fade.gsh",
                "Rhythm Heaven Fever [VAKE01]\\meta\\bootMovie.h264",
                "Rhythm Heaven Fever [VAKE01]\\meta\\bootLogoTex.tga",
                "Rhythm Heaven Fever [VAKE01]\\meta\\bootSound.btsnd"
If any of the file in list can't be downloaded, you will see the error in your screenshot.
For well-known reasons, these files can't be provided by this app directly.
I think that you may get more help in the GBATemp's thread.
