### ISSUE TITLE
语言文件无法正常使用，置于程序同一目录后，程序无法打开

### ISSUE THREAD

**Issue by JueLuo99** [timefox/TeconMoon-s-WiiVC-Injector-Mod#3]
#### 复现步骤
1. 在 Release 页面下载 mod 10 版本的主程序与文件
2. 解压并将二者置于同一目录
3. 双击程序运行，发现程序并不能正常出现窗口，任务管理器亦不能看到相关进程
4. 尝试下载源码后自行编译，发现程序可用
5. 将语言文件与自己编译的程序置于同一文件夹后，程序无法正常启动

#### 错误详情（如图所示）
编译器报告异常发生在 ```Utils.cs``` 文件的第 577~578 行
报告的异常为 ```System.NullReferenceException:“Object reference not set to an instance of an object.”```
![image](https://user-images.githubusercontent.com/25797524/80316152-b4b73480-882e-11ea-8fa4-f04a84e8ce73.png)

-----
能力有限，无法具体定位或解决问题。如果需要，乐意进一步提供更多信息
感谢开发者长期以来的维护！

**Comment by JueLuo99** [comment]
更换设备后程序可以正常运行，中文文字显示正常

**Comment by timefox** [comment]
@JueLuo99，这个可能和您使用的操作系统语言环境有关，很可能是Properties.Resources.ResourceManager.GetResourceSet(CultureInfo.CurrentCulture, false, false)返回了null，可以尝试将CultureInfo.CurrentCulture改为CultureInfo.InvariantCulture，或者将第二个参数改为true。因为我这边暂时没有测试环境，如果您可以帮忙试一下的话，请把结果告诉我，下一个版本就会修正这个问题。谢谢。

**Comment by JueLuo99** [comment]
@timefox ，尝试了提供的解决方案，可以解决问题，并且进一步确定了问题复现的条件

### 复现条件
操作系统：Windows10 64-bit 1909
在“设置”→“时间和语言”→“语言”中，修改“Windows 显示语言”选项后，会提示需要注销账号（如图所示状态）
![image](https://user-images.githubusercontent.com/25797524/80563068-71221d80-8a1c-11ea-8b80-ad0c3ce936ce.png)
此时不注销账号，运行程序，该 issue 描述的问题即会触发

### 可用的解决方法
将 ```Utils.cs``` 的第 578 行中的 ```CultureInfo.CurrentCulture``` 修改为 ```CultureInfo.InvariantCulture```

### 不可用的解决方法
将 ```Utils.cs``` 的第 578 行中的第二个参数改为 ```true```

-----
感谢开发者的耐心与指导！

**Comment by timefox** [comment]
@JueLuo99，感谢帮助测试和定位问题，检查了下代码，在导出翻译模板文件的时候也用到了类似的调用，我已经提交了修复。过两天看看能不能收到其他反馈一并进行改进，再发布一个release。

**Comment by timefox** [comment]
已在mod 11中修复。
