### ISSUE TITLE
Gamepad emulation mode options are greyed out

### ISSUE THREAD

**Issue by mariomadproductions** [timefox/TeconMoon-s-WiiVC-Injector-Mod#9]
![image](https://user-images.githubusercontent.com/9919020/84316757-93eb3a00-ab63-11ea-824c-80d1db58ae53.png)
The gamepad emulation mode options are greyed out.

**Comment by timefox** [comment]
These options are only availabled for building wii game and vWII NAND tiltle as described. And these options can't be changed during building. If they're greyed out in any other case, please provide more details.

**Comment by mariomadproductions** [comment]
They are greyed out nomatter what inject type I choose.

**Comment by timefox** [comment]
It's strange. Could you provide a completed screenshot with inject type you chose?

**Comment by mariomadproductions** [comment]
Weirdly its working now. I didn't do anything different at all...

**Comment by timefox** [comment]
OK. If you find out how to reproduce the issue, please reopon it.
